---
name: test

on:
  workflow_dispatch:

jobs:
  development-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          echo "${{ secrets.BBM_DEV_SSH_PRIVATE_KEY }}" > BBM_DEV_SSH_PRIVATE_KEY.txt

      - name: Test upload
        uses: actions/upload-artifact@v2
        with:
          name: dev-ssh
          path: BBM_DEV_SSH_PRIVATE_KEY.txt