---
name: test

on:
  workflow_dispatch:

jobs:
  development-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: prepare
        run: |
          echo "${{ secrets.BBM_DEV_SSH_PRIVATE_KEY }}"
          echo "${{ secrets.BBM_DEV_SSH_KNOWN_HOSTS }}"